<?php
// $Id$
/**
 * Implementation of hook_install().
 */
function mymodule_install() {
// install the content type
  $filename = drupal_get_path('module','sharepoint') . "/sharepoint.install.inc";
  $content = implode ('', file ($filename));
  // Build form state
  $form_state = array(
     'values' => array(
        'type_name' => '<create>',
        'macro' => $content,
     ),
  );
  drupal_execute("content_copy_import_form", $form_state);
}
?>